---
title: "Data Cleaning"
author: "Ethan Tenison"
date: "`r format(Sys.Date(), '%B %d, %Y') `"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readr)
library(janitor)
library(qualtRics)
library(Hmisc)
library(matchingR)


knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())


```

## Using Qualtrics to pull survey data
```{r qualtrics, message=FALSE, warning=FALSE}
qualtrics_api_credentials(
api_key = "0niuOUgg0bM7FJWr8f0eJzj1WbwcjCJfRFIW67x8", #you can find the api key on qualtrics
base_url = "ca1.qualtrics.com", 
install = FALSE
)

surveys <- all_surveys() #You've got check this first 
org_raw <- fetch_survey(surveyID = surveys$id[10])

stu_raw <- fetch_survey(surveyID = surveys$id[13])

```
## Org data cleaning 

```{r data_pull_old, message=FALSE, warning=FALSE}
org <- org_raw
  

colnames(org) <- label(org)

org <- org |>
  clean_names() |> 
  rename(time_commitment = realistically_how_much_time_do_you_expect_your_student_to_commit_per_week_working_on_your_assigned_project,
         transportation = does_your_candidate_need_to_have_access_to_transportation,
         flexible_hours = will_your_project_permit_flexible_work_hours,
         remote = will_your_candidate_be_able_to_work_remotely,
         nonprofit_experience = how_much_experience_working_or_volunteering_with_nonprofits_should_your_candidate_have_working_or_volunteering_for_nonprofits
         ) |> 
  select(organization,
         time_commitment,
         transportation,
         flexible_hours,
         remote,
         nonprofit_experience,
         39:67) |> 
  mutate(nonprofit_experience = case_when(
    nonprofit_experience == "No experience required" ~ "1",
    nonprofit_experience == "Less than 6 months" ~ "2",
    nonprofit_experience == "6 - 12 months" ~ "3",
    nonprofit_experience == "1 - 2 years" ~ "4",
    nonprofit_experience == "2 or more years" ~ "5",
  ))

names(org) <- gsub(
  pattern = "please_rate_how_relevant_the_following_technical_skills_are_to_your_project_",
  replacement = "",
  x = names(org))


org <- data.frame(lapply(org, function(x) {
                  gsub("1 - Not relevant", "1", x)
              }))

org <- data.frame(lapply(org, function(x) {
                  gsub("5 - Extremely relevant", "5", x)
              }))


org$time_commitment[org$time_commitment == "Less than 5 hours per week"] <- "1"
org$time_commitment[org$time_commitment == "5 - 10 hours per week"] <- "2"
org$time_commitment[org$time_commitment == "8 - 12 hours per week"] <- "3"
org$time_commitment[org$time_commitment == "10 - 15 hours per week"] <- "4"
org$time_commitment[org$time_commitment == "15 - 20 hours per week"] <- "5"


org <- org |> 
  mutate(across(6:31, as.numeric),
         time_commitment = as.numeric(time_commitment)) |> 
  select(organization, 6:31) #this part is only for the testing, i'll remove when I'm adding in disqualifiers

```

## Student Data Cleaning for Matching

```{r org_clean, message=FALSE, warning=FALSE}

stu <- stu_raw

colnames(stu) <- label(stu)

stu <- stu |> 
  clean_names() |> 
  filter(progress == 100) |> 
  select(
    first_name,
    last_name,
    realistically_how_much_time_can_you_commit_per_week_to_working_on_a_project,
    is_there_any_additional_information_regarding_your_availability_that_we_should_know_about,
    do_you_have_access_to_transportation,
    do_you_need_flexible_work_hours,
    do_you_need_the_ability_to_work_remotely,
    over_the_past_5_years_approximately_how_much_experience_have_you_had_working_or_directly_volunteering_with_nonprofit_organizations,
    64:88
  ) |>
    rename(
      time_commitment = realistically_how_much_time_can_you_commit_per_week_to_working_on_a_project,
      transportation = do_you_have_access_to_transportation,
      flexible_hours = do_you_need_flexible_work_hours, 
      remote = do_you_need_the_ability_to_work_remotely,
      nonprofit_experience = over_the_past_5_years_approximately_how_much_experience_have_you_had_working_or_directly_volunteering_with_nonprofit_organizations
    ) |> 
  mutate(nonprofit_experience = case_when(
    nonprofit_experience == "No experience (yet!)" ~ "1",
    nonprofit_experience == "Less than 6 months" ~ "2",
    nonprofit_experience == "6 - 12 months" ~ "3",
    nonprofit_experience == "1 - 2 years" ~ "4",
    nonprofit_experience == "2 or more years" ~ "5",
  ))

names(stu) <- gsub(pattern = "please_rate_your_experience_in_the_following_technical_skills_note_1_not_experienced_and_5_extremely_experienced_",
                  replacement = "",
                  x = names(stu))

stu$time_commitment[stu$time_commitment == "Less than 5 hours per week"] <- "1"
stu$time_commitment[stu$time_commitment == "5 - 10 hours per week"] <- "2"
stu$time_commitment[stu$time_commitment == "8 - 12 hours per week"] <- "3"
stu$time_commitment[stu$time_commitment == "10 - 15 hours per week"] <- "4"
stu$time_commitment[stu$time_commitment == "15 - 20 hours per week"] <- "5"

stu <- stu |> 
  mutate(across(8:33, as.numeric),
         time_commitment = as.numeric(time_commitment)) |> 
  mutate(name = paste0(first_name," ", last_name)) |> 
  select(name, 8:33) #just the test phase 

```


## Creating rating utility

```{r testing_utility}


    org1 <- org[2,] |>
      pivot_longer(2:27, names_to = "variable", values_to = "org_value")
    
    stu1 <- stu[21,] |>
      pivot_longer(2:27, names_to = "variable", values_to = "student_value") 
    
    match1 <- left_join(org1, stu1, by = "variable") |>
      mutate(
        subtracted = student_value - org_value,
        utility = case_when(
           subtracted <= 0 ~ 1,
           subtracted == 1 ~ .75,
           subtracted == 2 ~ .5,
           subtracted == 3 ~ .25,
           subtracted == 4 ~ 0
        ),
         utility = case_when(#if the org put 1 that means they get zero utility
           student_value == 1 ~ 0,
           TRUE ~ utility)
       )
    
    utility_score <- sum(match1$utility)

```


```{r utility}

#utility organizations                                    
column_names <- stu$name
row_names <- org$organization

uS <- matrix(nrow = length(org$organization),
             ncol = length(stu$name),
             dimnames = list(row_names, column_names))

for (i in 1:length(org$organization)) {
  for (j in 1:length(stu$name)) {
    org1 <- org[i,] |>
      pivot_longer(2:27, names_to = "variable", values_to = "org_value")
    
    stu1 <- stu[j,] |>
      pivot_longer(2:27, names_to = "variable", values_to = "student_value") 
    
    match1 <- left_join(org1, stu1, by = "variable") |>
      mutate(
        subtracted = student_value - org_value,
        utility = case_when(
           subtracted <= 0 ~ 1,
           subtracted == 1 ~ .75,
           subtracted == 2 ~ .5,
           subtracted == 3 ~ .25,
           subtracted == 4 ~ 0
        ),
         utility = case_when(#if the org put 1 that means they get zero utility
           student_value == 1 ~ 0,
           TRUE ~ utility)
       )
    
    utility_score <- sum(match1$utility)
    uS[i,j] <- utility_score
  }
}

#utility students 
row_names <- stu$name
column_names <- org$organization

uO <- matrix(nrow = length(stu$name),
             ncol = length(org$organization),
             dimnames = list(row_names, column_names))


for (j in 1:length(stu$name)) {
  for (i in 1:length(org$organization)) {
    org1 <- org[i, ] |>
      pivot_longer(2:27, names_to = "variable", values_to = "org_value")
    
    stu1 <- stu[j, ] |>
      pivot_longer(2:27, names_to = "variable", values_to = "student_value") 
    
    match1 <- left_join(stu1, org1, by = "variable") |>
      mutate(
        subtracted =  org_value - student_value,
        utility = case_when(
          subtracted <= 0 ~ 1,
           subtracted == 1 ~ .75,
           subtracted == 2 ~ .5,
           subtracted == 3 ~ .25,
           subtracted >= 4 ~ 0
        ),
         utility = case_when(#if the org put 1 that means they get zero utility
           org_value == 1 ~ 0,
           TRUE ~ utility)
      )
    
    utility_score <- sum(match1$utility)
    uO[j, i] <- utility_score
  }
}


```

```{r convert_to_rank}


for (i in 1:length(uO[,1])){
   uO[i,] <-rank(uO[i,],ties.method = "first")
}


for (i in 1:length(uS[,1])){
   uS[i,] <-rank(uS[i,], ties.method = "first")
}



```

## Using the Gale Shapley Algorithm

```{r gale_shapley, message=FALSE, warning=FALSE}

library(matchingR)
matching = galeShapley.marriageMarket(uS, uO)

str(matching)
```

